### ISSUE TITLE
Few questions regarding for Android

### ISSUE THREAD

**Issue by Joe23232** [i-schuetz/rust_android_ios#3]
Hi I have some questions regarding for the development of Android using the `crate`:
1. Am I able to make GUI applications?
2. Is there too much biolerplate code in it or is it simple and clean?
3. Is it easy to use or harder to use over something like Flutter or Android app Studio?

**Comment by i-schuetz** [comment]
> Am I able to make GUI applications?
Yes! You'll have 2 normal native apps (iOS and Android), so you can use the native tooling to build the UI (and anything else that's platform-specific).

> Is there too much biolerplate code in it or is it simple and clean?
This question is a bit broad. There is boilerplate to communicate between the apps and Rust. To keep things clean, you'd structure your app to hide this, as an implementation detail. Think about a high level API to communicate with the network or database.

> Is it easy to use or harder to use over something like Flutter or Android app Studio?
Since with this approach you have normal native apps, you'd probably use Android Studio to work with the Android app.
Flutter is a cross-platform framework that does "everything" (UI, domain logic, etc). I'd say that Flutter is easier, since you'd have to learn only one language and tooling (unless you have to develop plugins, but this is rare). You'll need some familiarity with the Android and iOS environment, but rather superficial. With the approach used here, you have to be proficient with native Android, native iOS and Rust.

Sorry for the late reply! For some reason I was not watching all the repo activity.

**Comment by i-schuetz** [comment]
> Am I able to make GUI applications?

Yes! You'll have 2 normal native apps (iOS and Android), so you can use the native tooling to build the UI (and anything else that's platform-specific).

> Is there too much biolerplate code in it or is it simple and clean?

This question is a bit broad. There is boilerplate to communicate between the apps and Rust. To keep things clean, you'd structure your app to hide this, as an implementation detail. Think about a high level API to communicate with the network or database.

> Is it easy to use or harder to use over something like Flutter or Android app Studio?

Since with this approach you have normal native apps, you'd probably use Android Studio to work with the Android app.
Flutter is a cross-platform framework that does "everything" (UI, domain logic, etc). I'd say that Flutter is easier, since you'd have to learn only one language and tooling (unless you have to develop plugins, but this is rare). You'll need some familiarity with the Android and iOS environment, but rather superficial. With the approach used here, you have to be proficient with native Android, native iOS and Rust.

Sorry for the late reply! For some reason I was not watching all the repo activity.

**Comment by Joe23232** [comment]
Hi @i-schuetz thank you for your reply :)

> Sorry for the late reply! For some reason I was not watching all the repo activity.

It's ok mate :)

---

I wanted to ask you additional questions.

1. Is it a low level or high level library/crate?
2. Are there any man pages available for this crate?
3. How well maintained is this repo?

**Comment by i-schuetz** [comment]
It's just an example. Not a crate. Please read the README.

**Comment by i-schuetz** [comment]
This project is not a library. It's an example you'd have to build upon. Please read the README.

**Comment by Joe23232** [comment]
Ah I see, thanks
